### PR TITLE
Prevent rendering days without timetable (#8)

### PR DESCRIPTION
**Pull request by wallchuck**

### CODE REVIEW

**Comment by wallchuck** [comment]
Could you please give me a hint where should I check? I'm not too familiar with this particular mechanism.

**Comment by andreasonny83** [comment]
Nevermind, looks like it's working now. Thank you

**Comment by wallchuck** [comment]
My pleasure! It might have been just a random issue with the deploy. Nice looking website by the way! :)

**Comment by andreasonny83** [comment]
closes #8

**Pull request merged**
